import { ReduxProvider } from '@/app/Provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from './components/Sidebar'
import Topbar from './components/Topbar'
import Alert from './components/Alert'
import GoogleAnalytics from './GoogleAnalytics'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Job Pulse',
  description: 'Generated by create next app',
  icons: {
    icon: ['/icon.ico'],
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="">
        <link rel="icon" href="/icon.ico" sizes="any" />
        <GoogleAnalytics />
        <ReduxProvider>
          <div className=' min-h-screen'>
            <div className=' flex flex-col'>
              <Alert />
              <Topbar />
              {children}
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  )
}
